apiVersion: v1
data:
  abc: ZWVl
kind: Secret
metadata:
  creationTimestamp: "2020-12-30T14:01:39Z"
  managedFields:
  - apiVersion: v1
    fieldsType: FieldsV1
    fieldsV1:
      f:data:
        .: {}
        f:abc: {}
      f:type: {}
    manager: oc
    operation: Update
    time: "2020-12-30T14:01:39Z"
  name: test1
  namespace: default
  resourceVersion: "62997"
  selfLink: /api/v1/namespaces/default/secrets/test1
  uid: ff4fef4f-f4ba-495b-9b52-c2e61ae08f5f
type: Opaque
